# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '2chan_scope_ui.ui'
#
# Created: Tue Jun 11 19:23:20 2013
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(800, 600)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.graphicsView = PlotWidget(self.centralwidget)
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.verticalLayout.addWidget(self.graphicsView)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 100))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.stacked_plot = QtGui.QRadioButton(self.groupBox_2)
        self.stacked_plot.setObjectName(_fromUtf8("stacked_plot"))
        self.buttonGroup = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.stacked_plot)
        self.verticalLayout_2.addWidget(self.stacked_plot)
        self.xy_plot = QtGui.QRadioButton(self.groupBox_2)
        self.xy_plot.setObjectName(_fromUtf8("xy_plot"))
        self.buttonGroup.addButton(self.xy_plot)
        self.verticalLayout_2.addWidget(self.xy_plot)
        self.gridLayout.addWidget(self.groupBox_2, 0, 2, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label = QtGui.QLabel(self.groupBox_3)
        self.label.setMargin(8)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_3)
        self.label_2.setMargin(8)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.iOffsetBox = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.iOffsetBox.setMinimumSize(QtCore.QSize(100, 0))
        self.iOffsetBox.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.iOffsetBox.setMinimum(-100.0)
        self.iOffsetBox.setMaximum(100.0)
        self.iOffsetBox.setObjectName(_fromUtf8("iOffsetBox"))
        self.gridLayout_2.addWidget(self.iOffsetBox, 0, 1, 1, 1)
        self.qOffsetBox = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.qOffsetBox.setMinimumSize(QtCore.QSize(100, 0))
        self.qOffsetBox.setMinimum(-100.0)
        self.qOffsetBox.setMaximum(100.0)
        self.qOffsetBox.setObjectName(_fromUtf8("qOffsetBox"))
        self.gridLayout_2.addWidget(self.qOffsetBox, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_3, 0, 3, 1, 3)
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.startButton = QtGui.QPushButton(self.groupBox_4)
        self.startButton.setObjectName(_fromUtf8("startButton"))
        self.verticalLayout_3.addWidget(self.startButton)
        self.gridLayout.addWidget(self.groupBox_4, 0, 7, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.qGainBox = QtGui.QDoubleSpinBox(self.groupBox_5)
        self.qGainBox.setMinimumSize(QtCore.QSize(100, 0))
        self.qGainBox.setObjectName(_fromUtf8("qGainBox"))
        self.gridLayout_3.addWidget(self.qGainBox, 1, 1, 1, 1)
        self.iGainBox = QtGui.QDoubleSpinBox(self.groupBox_5)
        self.iGainBox.setMinimumSize(QtCore.QSize(100, 0))
        self.iGainBox.setObjectName(_fromUtf8("iGainBox"))
        self.gridLayout_3.addWidget(self.iGainBox, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox_5)
        self.label_3.setMargin(8)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_5)
        self.label_4.setMargin(8)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_5, 0, 6, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 8, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "2 Chan Scope", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Plot Type", None, QtGui.QApplication.UnicodeUTF8))
        self.stacked_plot.setText(QtGui.QApplication.translate("MainWindow", "Stacked Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.xy_plot.setText(QtGui.QApplication.translate("MainWindow", "XY Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Vertical Offsets", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "I offset", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Q offset", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("MainWindow", "Controls", None, QtGui.QApplication.UnicodeUTF8))
        self.startButton.setText(QtGui.QApplication.translate("MainWindow", "Pause", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("MainWindow", "Gains", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "I Gain", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Q Gain", None, QtGui.QApplication.UnicodeUTF8))

from pyqtgraph import PlotWidget
